# Generated by Django 4.2 on 2023-05-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_sup',
            new_name='is_sub',
        ),
    ]
